name: harputil
version: 0.1.0.0
github: "jonlaing/harputil"
license: BSD3
author: "Jon Laing"
maintainer: "jon@jonlaing.io"
copyright: "2019 Jon Laing"

extra-source-files:
  - README.md
  - ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/jonlaing/harputil#readme>

dependencies:
  - base >= 4.7 && < 5
  - text

library:
  source-dirs: src

executables:
  harputil-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - harputil

tests:
  harputil-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - harputil
      - hspec
